### ISSUE TITLE
Bukkit: Missing / when you try to execute /help <registered command>

### ISSUE THREAD

**Issue by DevCyntrix** [Incendo/cloud-minecraft#7]
Hey,
by default minecraft has a / before the command in the usage. Cloud doesn't make it. Maybe you could add this.

I am using annotations and the bukkti platform

**Comment by jpenilla** [comment]
This is working as intended - slash is not always required, for example when executing commands from the console. You will notice that built-in Minecraft commands also lack a preceding slash in their Bukkit usage strings.
