### ISSUE TITLE
Velocity not sending usage if invalid argument, forwards command to backend instead

### ISSUE THREAD

**Issue by bridgelol** [Incendo/cloud-minecraft#71]
Unsure if this is intended but this behavior surely did change after moving from 1.8.4 to 2.0.0-SNAPSHOT

**Comment by jpenilla** [comment]
This is not new in v2, it's Velocity behavior to forward invalid commands insofar as Brigadier is concerned to the backend. This behavior is not under cloud's control.

**Comment by bridgelol** [comment]
> This is not new in v2, it's Velocity behavior to forward invalid commands insofar as Brigadier is concerned to the backend. This behavior is not under cloud's control.

![image](https://github.com/Incendo/cloud-minecraft/assets/29434554/9013fbda-8933-485a-b7d7-9f89d86cf72b)

**Comment by bridgelol** [comment]
Am I implementing something wrong here?

**Comment by jpenilla** [comment]
This is because the command structure passed to Brigadier is now more accurate. See the conversation below from the Discord:

![Screenshot 2024-05-28 at 4 45 21 PM](https://github.com/Incendo/cloud-minecraft/assets/11360596/8fbbdc72-023c-43e7-86d1-2192b2d376ec)
