### ISSUE TITLE
Modern Paper command doesn't support parsing asian languages or specific symbols (like '?')

### ISSUE THREAD

**Issue by nostalfinals** [Incendo/cloud-minecraft#89]
I'm using the latest snapshot of `cloud` and `cloud-minecraft`.

When I try to add an argument to my command that may contain Chinese characters, the command doesn't work.

![image](https://github.com/user-attachments/assets/c45f63fb-9ead-44a9-a33f-863227ea94b8)
![image](https://github.com/user-attachments/assets/1b7ff8bf-3f29-43d7-b322-c818c685f81d)

In `SINGLE` mode, `StringParser` seems to read all contents from the `CommandInput`. I suspect this issue is related to the platform's `CommandManager`.

```java
public @NonNull ArgumentParseResult<String> parse(final @NonNull CommandContext<C> commandContext, final @NonNull CommandInput commandInput) {
    if (this.stringMode == StringParser.StringMode.SINGLE) {
        return ArgumentParseResult.success(commandInput.readString());
    } else {
        return this.stringMode == StringParser.StringMode.QUOTED ? this.parseQuoted(commandContext, commandInput) : this.parseGreedy(commandInput);
    }
}
```

When I switch to `LegacyPaperCommandManager` and register a legacy Paper brigadier, the command works correctly.

```kotlin
lateinit var commandManager: LegacyPaperCommandManager<CommandSender>
commandManager = LegacyPaperCommandManager.createNative(this, ExecutionCoordinator.asyncCoordinator())
commandManager.registerLegacyPaperBrigadier()
```

![image](https://github.com/user-attachments/assets/921d40ec-5c13-45ca-b61f-1485e820f317)

Here is how I create my command:

```kotlin
commandManager.commandBuilder("home")
    .required("name", StringParser.stringParser())
    .suspendingHandler {
        ...
    }
```

**Comment by jpenilla** [comment]
Legacy brig only appears to work as it does nothing (Paper never re-implemented the old API on 1.20.6+).
https://github.com/Mojang/brigadier/blob/master/src/main/java/com/mojang/brigadier/StringReader.java#L169-L175
Mojang is very restrictive on what is allowed in unquoted strings. You must map your argument to a Brigadier type that accepts Chinese characters, like greedy or quoted string.
